<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-BUD55MU" failures="1" tests="2" name="Test" time="22.266" errors="0" timestamp="2022-08-30T20:24:42 IST">
  <testcase classname="TestCases.VerifyLoginTestCase" name="login" time="0.335">
    <failure type="java.lang.AssertionError" message="expected [Please check your username . If you still can&amp;apos;t log in, contact your Salesforce administrator.] but found [Please check your username and password. If you still can&amp;apos;t log in, contact your Salesforce administrator.]">
      <![CDATA[java.lang.AssertionError: expected [Please check your username . If you still can't log in, contact your Salesforce administrator.] but found [Please check your username and password. If you still can't log in, contact your Salesforce administrator.]
at Resources.commonUtilities.HandleAssert(commonUtilities.java:23)
at TestCases.VerifyLoginTestCase.login(VerifyLoginTestCase.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase classname="TestCases.VerifySignUpTestCases" name="SignUp" time="6.628"/>
</testsuite> <!-- Test -->
